export default {
  iclog: require("../assets/images/logo.png"),
  icBanner1: require("../assets/images/banner1.jpeg"),
  icBanner2: require("../assets/images/banner2.jpeg"),
  icBanner3: require("../assets/images/banner3.jpeg"),
  icBack: require("../assets/images/arrow.png"),
  icGoogle: require("../assets/images/google.png"),
  icHide: require("../assets/images/visibilityoff.png"),
  icView: require("../assets/images/eyevisible.png"),
  icnotification: require("../assets/images/notification.png"),
  icProfile: require("../assets/images/profile.jpg"),
  icEaring: require("../assets/images/earning.png"),
  icInvestment: require("../assets/images/investment.png"),
  icIncrease: require("../assets/images/increase.png"),
  ichome: require("../assets/images/house.png"),
  icdelay:require("../assets/images//Delay.jpeg"),
  icHolders: require("../assets/images/Holders.jpeg"),
  icinstant: require("../assets/images/instant.jpeg"),
  icorder: require("../assets/images/orders.jpeg"),
  icsip: require("../assets/images/sip.jpeg"),
  icbellicon: require("../assets/images/bellicon.jpeg"),
  iccoin1: require("../assets/images/coins1.jpeg"),
  iccoin2: require("../assets/images/coins2.jpeg"),
  iccoin3: require("../assets/images/coin3.jpeg"),
  icEth: require("../assets/images/Eth.jpeg"),
  icripple: require("../assets/images/ripple.jpeg"),
  icpercent: require("../assets/images/percent.jpeg"),
  icbit: require("../assets/images/bit.jpeg"),
  icSreach: require("../assets/images/search.png"),
  icDoyo: require("../assets/images/doyo.jpeg"),
  icarrowright: require("../assets/images/arrow-right.png"),
  icspart: require("../assets/images/Spart.jpeg"),
  icholo: require("../assets/images/holo.jpeg"),
  iclargecap: require("../assets/images/largeCaps.jpeg"),
  icnavigation: require("../assets/images/navigate.png"),
  icmostTrade: require("../assets/images/mosttraded.jpeg"),
  icassignment: require("../assets/images/assignment.png"),
  icglass: require("../assets/images/glass.jpeg"),
  iclearning: require("../assets/images/learning.png"),
  icQuick: require("../assets/images/Quick.jpeg"),
  icEasy: require("../assets/images/Easy.png"),
  icLock: require("../assets/images/Lock.png"),


  
};

