export default {
  create_Account: "Create an account",
  Login: "Log in",
  fullName: "Full name",
  Email: "Email ID",
  Create_pass: "Create Password",
  Agree: "By proceeding, you agree to",
  Services: " Terms of Services ",
  and: " and ",
  Policy: " Privacy Policy",
  Continue: "Continue",
  or: "Or",
  Google_account: "Create account with Google",
  Login_account: "Login to your account",
  Pass: "Password",
  Forgot: "Forgot Password",
  OTP: "Enter OTP via SMS or Google Authenticator App from Your registered  device",
  WaitOTP: "Didn't receive OTP? wait for",
  Help:"Help",
};
