export default {
  create_Account: "Create an account",
  Login: "Log in",
  fullName: "Full name",
  Email: "Email ID",
  Create_pass: "Create Password",
  Agree: "By proceeding, you agree to",
  Services: " Terms of Services ",
  and: " and ",
  Policy: " Privacy Policy",
  Continue: "Continue",
  or: "Or",
  Google_account: "Create account with Google",
  Login_account: "Login to your account",
  Pass: "Password",
  Forgot: "Forgot Password",
  OTP: "Enter OTP via SMS or Google Authenticator App from Your registered  device",
  WaitOTP: "Didn't receive OTP? wait for",
  Help: "Help",
  Large_Caps: "Large Caps",
  Top_tokens: "Top tokens by market Capitalisation",
  Most_Traded: "Most Traded",
  Top_volume: "Top tokens by volume in the past of 24 hours",
  INTRODUCING_EARN: "INTRODUCING EARN",
  Get_Returns: "Get Returns on your Cryptos",
  Earns_while: "Earns while you HODL , at no added cost",
  users_invested: "users have already invested",
  Start_earnings: "Start earnings within 7 days",
  Track_daily: "Track daily returns",
  No_Periods: "No lock in Periods",
  Instant_Buy: "Instant Buy",
  Alerts: "Alerts",
  SIP: "SIP",
  Orders: "Orders",
  Recently_Listed: "Recently Listed",
  dodo: "DODO",
  Defi: "DeFi",
  price1: "₹73.45",
  Startregy: "Startregy",
  STG: "STG",
  Interoperability: "Interoperability",
  price2: "₹16.75",
  HOLO: "HOLO",
  HOT: "HOT",
  Layer_lockchain: "Layer-1-Blockchain",
  price3: "₹0.45",
  Paste: "Paste",
  You_investments: "You don't have any investments!",
  Start_investing: "Start investing in these most popular coins",
  Bitcoin: "Bitcoin",
  BTC: "BTC",
  users_Bitcoin_investment:
    " 70% users perferred Bitcoin for their first investment",
  Ethererum: "Ethererum",
  ETH: "ETH",
  Ripple: "Ripple",
  XRP: "XRP",
  See_coins: "See all coins",
  Shortlist_cryptos: "Shortlist your favourite cryptos",
  Shortlist_favourite:
    "Tab on the star icon anywhere in the app to Shortlist your favourite cryptos",
  Explore_Catogeries: "Explore Catogeries",
  Grainers: "Grainers",
  Losers: "Losers",
  New: "New",
  All_Catogeries: "All Catogeries",
};
